a=int(input("Enter a first number: "))
b=int(input("Enter a second number: "))
print("________ARTHEMATIC OPERATION_______________")
print(f"ADDITION: {a}+{b}={a+b}")
print(f"SUBTRATION: {a}-{b}={a-b}")
print(f"MULTIPLICATION: {a}*{b}={a*b}")
print(f"DIVISION: {a}/{b}={a/b}")
print(f"REMAIDER/MODULUS: {a}%{b}={a%b}")
print(f"EXPONENTIAL: {a}**{b}={a**b}")
print(f"FLOOR DIVISIO: {a}//{b}={a//b}")
